In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv(r"C:\Users\Phavour\Downloads\Personal Python-ML project\Simplilearn\Workspace\Titanic With Naive bayes\train.csv")
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
dataset = dataset.drop(['PassengerId','Name','Ticket','Cabin', 'Embarked'],axis=1)
dataset

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

In [5]:
Sex = pd.get_dummies(dataset.Sex,dtype='int64')

In [6]:
dataset = pd.concat([dataset, Sex],axis=1)
dataset

Survived  Pclass     Sex   Age  SibSp  Parch     Fare  female  male
0           0       3    male  22.0      1      0   7.2500       0     1
1           1       1  female  38.0      1      0  71.2833       1     0
2           1       3  female  26.0      0      0   7.9250       1     0
3           1       1  female  35.0      1      0  53.1000       1     0
4           0       3    male  35.0      0      0   8.0500       0     1
..        ...     ...     ...   ...    ...    ...      ...     ...   ...
886         0       2    male  27.0      0      0  13.0000       0     1
887         1       1  female  19.0      0      0  30.0000       1     0
888         0       3  female   NaN      1      2  23.4500       1     0
889         1       1    male  26.0      0      0  30.0000       0     1
890         0       3    male  32.0      0      0   7.7500       0     1

[891 rows x 9 columns]

In [13]:
dataset = dataset.drop('Sex',axis=1)

In [14]:
dataset.Age = dataset.Age.fillna(dataset.Age.mean())
dataset.isna().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
female      0
male        0
dtype: int64

In [15]:
X = dataset.drop('Survived',axis=1)
y = dataset.Survived

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print(len(x_train))
print(len(x_test))

668
223


In [20]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [21]:
model.score(x_test, y_test)

0.7982062780269058

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, model.predict(x_test))

array([[113,  21],
       [ 24,  65]], dtype=int64)

In [25]:
y_test.head(10)

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: Survived, dtype: int64

In [27]:
model.predict(x_test[:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [28]:
model.predict_proba(x_test[:10])

array([[9.84359321e-01, 1.56406786e-02],
       [9.69991444e-01, 3.00085562e-02],
       [9.82726080e-01, 1.72739199e-02],
       [7.01952895e-03, 9.92980471e-01],
       [2.96313426e-02, 9.70368657e-01],
       [8.55688646e-04, 9.99144311e-01],
       [3.85365228e-02, 9.61463477e-01],
       [9.95042875e-01, 4.95712481e-03],
       [2.91213317e-02, 9.70878668e-01],
       [4.26951883e-03, 9.95730481e-01]])