In [35]:
import tensorflow as tf

In [36]:

mnist = tf.keras.datasets.mnist
(X_train,y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0


In [37]:
models = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                     tf.keras.layers.Dense(128, activation='relu'),
                                     tf.keras.layers.Dropout(0.2),
                                     tf.keras.layers.Dense(10)
                                     ])

c:\Users\Phavour\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [38]:
predictions = models(X_train[:1]).numpy()

In [39]:
predictions

array([[-0.05894896,  0.06443497, -0.09591267,  0.16969202,  0.18341649,
        -0.21054022,  0.13737403,  0.10346042,  0.2129535 , -0.20274022]],
      dtype=float32)

In [40]:
tf.nn.softmax(predictions).numpy()

array([[0.09043793, 0.1023141 , 0.08715604, 0.11367059, 0.11524141,
        0.07771688, 0.11005571, 0.10638589, 0.11869606, 0.07832544]],
      dtype=float32)

In [41]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.554683

In [42]:
models.compile(optimizer='adam', metrics=['accuracy'],loss=loss_fn)
models.fit(X_train, y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8600 - loss: 0.4770
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9552 - loss: 0.1500
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9672 - loss: 0.1078
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9731 - loss: 0.0861
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9768 - loss: 0.0729


In [43]:
models.evaluate(X_test, y_test,verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9762 - loss: 0.0779


[0.07794798165559769, 0.9761999845504761]

In [46]:
prob = tf.keras.Sequential([models, tf.keras.layers.Softmax()])
prob(X_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.0554761e-08, 7.2393957e-10, 3.6039928e-06, 1.2266237e-04,
        7.6795591e-11, 5.1988042e-08, 1.0034717e-13, 9.9986744e-01,
        1.6823319e-07, 6.0718021e-06],
       [7.9579529e-08, 1.4510538e-03, 9.9841714e-01, 1.2742248e-04,
        2.7405530e-13, 4.9279697e-07, 4.8699206e-07, 1.3061143e-11,
        3.3903032e-06, 2.4710923e-11],
       [1.7766903e-06, 9.9915409e-01, 1.0103070e-04, 1.2994038e-05,
        5.8372865e-05, 7.4023222e-07, 5.2680116e-06, 6.3218258e-04,
        3.2511551e-05, 1.1227812e-06]], dtype=float32)>